java_major = 21
schema = "timefold-sdk/1"
version = "2.6.0"

[[jars]]
artifact = "timefold_HdrHistogram"
filename = "HdrHistogram-2.2.2.jar"
group = "org.hdrhistogram"
name = "HdrHistogram"
pom_url = "https://repo.maven.apache.org/maven2/org/hdrhistogram/HdrHistogram/2.2.2/HdrHistogram-2.2.2.pom"
sha256 = "22d1d4316c4ec13a68b559e98c8256d69071593731da96136640f864fa14fad8"
version = "2.2.2"
[[jars]]
artifact = "timefold_angus_activation"
filename = "angus-activation-2.0.3.jar"
group = "org.eclipse.angus"
name = "angus-activation"
pom_url = "https://repo.maven.apache.org/maven2/org/eclipse/angus/angus-activation/2.0.3/angus-activation-2.0.3.pom"
sha256 = "a6bd35c538cf90fff941ad6258c40c08fca0b5c9c3f536c657114f27ce0527a7"
version = "2.0.3"
[[jars]]
artifact = "timefold_gizmo2"
filename = "gizmo2-2.1.1.jar"
group = "io.quarkus.gizmo"
name = "gizmo2"
pom_url = "https://repo.maven.apache.org/maven2/io/quarkus/gizmo/gizmo2/2.1.1/gizmo2-2.1.1.pom"
sha256 = "777af2f3b98bbc238938e95c0679c5a1473ec86513e1b88c36901a30c58c9b8e"
version = "2.1.1"
[[jars]]
artifact = "timefold_istack_commons_runtime"
filename = "istack-commons-runtime-4.1.2.jar"
group = "com.sun.istack"
name = "istack-commons-runtime"
pom_url = "https://repo.maven.apache.org/maven2/com/sun/istack/istack-commons-runtime/4.1.2/istack-commons-runtime-4.1.2.pom"
sha256 = "7fd6792361f4dd00f8c56af4a20cecc0066deea4a8f3dec38348af23fc2296ee"
version = "4.1.2"
[[jars]]
artifact = "timefold_jakarta.activation_api"
filename = "jakarta.activation-api-2.1.4.jar"
group = "jakarta.activation"
name = "jakarta.activation-api"
pom_url = "https://repo.maven.apache.org/maven2/jakarta/activation/jakarta.activation-api/2.1.4/jakarta.activation-api-2.1.4.pom"
sha256 = "c9db52100ce6c8aac95cc39075f95720d2e561b11f8051b81c121ad4effd7004"
version = "2.1.4"
[[jars]]
artifact = "timefold_jakarta.xml.bind_api"
filename = "jakarta.xml.bind-api-4.0.5.jar"
group = "jakarta.xml.bind"
name = "jakarta.xml.bind-api"
pom_url = "https://repo.maven.apache.org/maven2/jakarta/xml/bind/jakarta.xml.bind-api/4.0.5/jakarta.xml.bind-api-4.0.5.pom"
sha256 = "5e489b6c874c4119e003ff1403db523ee3a8959ec499f3de29e77245efccf216"
version = "4.0.5"
[[jars]]
artifact = "timefold_jaxb_core"
filename = "jaxb-core-4.0.9.jar"
group = "org.glassfish.jaxb"
name = "jaxb-core"
pom_url = "https://repo.maven.apache.org/maven2/org/glassfish/jaxb/jaxb-core/4.0.9/jaxb-core-4.0.9.pom"
sha256 = "6b014df25d22c8446cc2df0a378c5b2137747f197a731d99eb24c756b26f7e8d"
version = "4.0.9"
[[jars]]
artifact = "timefold_jaxb_runtime"
filename = "jaxb-runtime-4.0.9.jar"
group = "org.glassfish.jaxb"
name = "jaxb-runtime"
pom_url = "https://repo.maven.apache.org/maven2/org/glassfish/jaxb/jaxb-runtime/4.0.9/jaxb-runtime-4.0.9.pom"
sha256 = "93e09b7316b6af68d6e2083e4c297daf28e8957f45d725077af812c0b12c39ab"
version = "4.0.9"
[[jars]]
artifact = "timefold_jboss_logging"
filename = "jboss-logging-3.6.0.Final.jar"
group = "org.jboss.logging"
name = "jboss-logging"
pom_url = "https://repo.maven.apache.org/maven2/org/jboss/logging/jboss-logging/3.6.0.Final/jboss-logging-3.6.0.Final.pom"
sha256 = "924529a679ad76a4665115c47f053e47c6fd272f59a632ba70db481c925ef7a2"
version = "3.6.0.Final"
[[jars]]
artifact = "timefold_jdk_classfile_backport"
filename = "jdk-classfile-backport-26.jar"
group = "io.smallrye.classfile"
name = "jdk-classfile-backport"
pom_url = "https://repo.maven.apache.org/maven2/io/smallrye/classfile/jdk-classfile-backport/26/jdk-classfile-backport-26.pom"
sha256 = "2eb2741b04c632ca361fb7dc947e993785639e76233129e84b2c85d618ae12ca"
version = "26"
[[jars]]
artifact = "timefold_jspecify"
filename = "jspecify-1.0.1.jar"
group = "org.jspecify"
name = "jspecify"
pom_url = "https://repo.maven.apache.org/maven2/org/jspecify/jspecify/1.0.1/jspecify-1.0.1.pom"
sha256 = "070d75f261fe4c5b8202508366715f7f2d4660f88c8ef7e6d3575e48c9683b66"
version = "1.0.1"
[[jars]]
artifact = "timefold_micrometer_commons"
filename = "micrometer-commons-1.17.0.jar"
group = "io.micrometer"
name = "micrometer-commons"
pom_url = "https://repo.maven.apache.org/maven2/io/micrometer/micrometer-commons/1.17.0/micrometer-commons-1.17.0.pom"
sha256 = "03919dc71e2417ec4b5c254c4ba924963c972e124190f73cdcb68ed51c6eede6"
version = "1.17.0"
[[jars]]
artifact = "timefold_micrometer_core"
filename = "micrometer-core-1.17.0.jar"
group = "io.micrometer"
name = "micrometer-core"
pom_url = "https://repo.maven.apache.org/maven2/io/micrometer/micrometer-core/1.17.0/micrometer-core-1.17.0.pom"
sha256 = "73503e701a377fafeaf33b71b9b8910a8d7884cbba88ab27971b33b3753b65aa"
version = "1.17.0"
[[jars]]
artifact = "timefold_micrometer_observation"
filename = "micrometer-observation-1.17.0.jar"
group = "io.micrometer"
name = "micrometer-observation"
pom_url = "https://repo.maven.apache.org/maven2/io/micrometer/micrometer-observation/1.17.0/micrometer-observation-1.17.0.pom"
sha256 = "2fc95a327578d3b2a81c3ff40e646a4a21e46b0153ccbbf91690142bf80d9661"
version = "1.17.0"
[[jars]]
artifact = "timefold_slf4j_api"
filename = "slf4j-api-2.0.18.jar"
group = "org.slf4j"
name = "slf4j-api"
pom_url = "https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/2.0.18/slf4j-api-2.0.18.pom"
sha256 = "44508fd1576500688c790b190acdd16fec4f8c79a3e0b900afd70503cf055f55"
version = "2.0.18"
[[jars]]
artifact = "timefold_slf4j_simple"
filename = "slf4j-simple-2.0.17.jar"
group = "org.slf4j"
name = "slf4j-simple"
pom_url = "https://repo.maven.apache.org/maven2/org/slf4j/slf4j-simple/2.0.17/slf4j-simple-2.0.17.pom"
sha256 = "ddfea59ac074c6d3e24ac2c38622d2d963895e17f70b38ed4bdae4d780be6964"
version = "2.0.17"
[[jars]]
artifact = "timefold_smallrye_common_constraint"
filename = "smallrye-common-constraint-2.16.0.jar"
group = "io.smallrye.common"
name = "smallrye-common-constraint"
pom_url = "https://repo.maven.apache.org/maven2/io/smallrye/common/smallrye-common-constraint/2.16.0/smallrye-common-constraint-2.16.0.pom"
sha256 = "9ce104ceb2284024fcf8d427ad2abcbb533e6afedf517a2b8727269f6a5920a6"
version = "2.16.0"
[[jars]]
artifact = "timefold_smallrye_common_resource"
filename = "smallrye-common-resource-2.16.0.jar"
group = "io.smallrye.common"
name = "smallrye-common-resource"
pom_url = "https://repo.maven.apache.org/maven2/io/smallrye/common/smallrye-common-resource/2.16.0/smallrye-common-resource-2.16.0.pom"
sha256 = "00fefb18cf87306ad8427d444c8f098de5c64c82183579b0b7d7c14f28308413"
version = "2.16.0"
[[jars]]
artifact = "timefold_timefold_solver_core"
filename = "timefold-solver-core-2.6.0.jar"
group = "ai.timefold.solver"
name = "timefold-solver-core"
pom_url = "https://repo.maven.apache.org/maven2/ai/timefold/solver/timefold-solver-core/2.6.0/timefold-solver-core-2.6.0.pom"
sha256 = "6c5d37d1d94d21d7fb687bd78e446cff71b6314854f98ad32b3045a7300d1e0f"
version = "2.6.0"
[[jars]]
artifact = "timefold_txw2"
filename = "txw2-4.0.9.jar"
group = "org.glassfish.jaxb"
name = "txw2"
pom_url = "https://repo.maven.apache.org/maven2/org/glassfish/jaxb/txw2/4.0.9/txw2-4.0.9.pom"
sha256 = "d6343e5945d87266ca4e8974a0a2a876e1bd147a00fb65ed3f2e1a3a00f3a82a"
version = "4.0.9"
